# -*- coding: utf-8 -*-
"""Final projcet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AMuxVvXBBNkSvWiDk2r04Ivt3vOTRiii
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data
data = pd.read_csv('finalproject_Pizza.csv')

# Convert the date column to datetime
data['date'] = pd.to_datetime(data['date'])

# Sidebar for filtering
st.sidebar.header('Filter Options')
date_range = st.sidebar.date_input('Select Date Range:', [data['date'].min(), data['date'].max()])
selected_type = st.sidebar.multiselect('Select Pizza Type:', options=data['type'].unique(), default=data['type'].unique())
selected_size = st.sidebar.multiselect('Select Pizza Size:', options=data['size'].unique(), default=data['size'].unique())

# Filter data based on selections
filtered_data = data[(data['date'] >= pd.to_datetime(date_range[0])) &
                    (data['date'] <= pd.to_datetime(date_range[1])) &
                    (data['type'].isin(selected_type)) &
                    (data['size'].isin(selected_size))]

# Title
st.title('Pizza Sales Analysis')

# Total sales over time
st.subheader('Total Sales Over Time')
sales_over_time = filtered_data.groupby('date')['price'].sum().reset_index()
fig, ax = plt.subplots()
ax.plot(sales_over_time['date'], sales_over_time['price'])
ax.set_xlabel('Date')
ax.set_ylabel('Total Sales')
ax.set_title('Total Sales Over Time')
st.pyplot(fig)

# Sales by pizza type and size
st.subheader('Sales by Pizza Type and Size')
sales_by_type_size = filtered_data.groupby(['type', 'size'])['price'].sum().unstack().fillna(0)
fig, ax = plt.subplots()
sales_by_type_size.plot(kind='bar', stacked=True, ax=ax)
ax.set_xlabel('Pizza Type')
ax.set_ylabel('Total Sales')
ax.set_title('Sales by Pizza Type and Size')
st.pyplot(fig)

# Histogram of pizza prices
st.subheader('Distribution of Pizza Prices')
fig, ax = plt.subplots()
sns.histplot(filtered_data['price'], bins=10, ax=ax)
ax.set_xlabel('Price')
ax.set_ylabel('Count')
ax.set_title('Distribution of Pizza Prices')
st.pyplot(fig)

# Pie chart of sales by pizza type
st.subheader('Sales Proportion by Pizza Type')
sales_by_type = filtered_data.groupby('type')['price'].sum().reset_index()
fig, ax = plt.subplots()
ax.pie(sales_by_type['price'], labels=sales_by_type['type'], autopct='%1.1f%%')
ax.set_title('Sales Proportion by Pizza Type')
st.pyplot(fig)

# Display filtered data
st.subheader('Filtered Data')
st.write(filtered_data)
